### ISSUE TITLE
Server Rendering

### ISSUE THREAD

**Issue by mvalipour** [gajus/react-outside-event#2]
In the case of server rendering `window` is not available in node and hence will error.

Of course we could chose not to wrap the component:

```
export default typeof window === 'undefined' ? Player : ReactOutsideEvent(Player, ['click']);
```

But to me, it makes sense to do this in the library itself.

I.e. Return the `Target` unwrapped if `typeof window === 'undefined'`

**Comment by gajus** [comment]
What are you using to render the application?

It works with https://github.com/gajus/isomorphic-webpack. I'd expect every server side rendering engine to emulate browser for this purpose.

**Comment by mvalipour** [comment]
I'm hooking directly into `react-dom/server`, but interesting insight. I'll look at available engines. I'm sure they help for things beyond this! 

Ta! :)

**Comment by gajus** [comment]
isomorphic-webpack is in alpha stage. Nothing is broken, I am using it in production, but ... I wouldn't dare to advertise it as production ready simply because it hasn't passed yet the [rule of three](https://blog.codinghorror.com/rule-of-three/).

If you are planning on using it, I'd be happy to provide you support. Raise an issue as you have questions and ping me.

Alternatively, consider https://react-server.io.
